services:
  localstack:
    image: localstack/localstack:3.0
    environment:
      - SERVICES=sqs,dynamodb,lambda,iam
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEBUG=1
    ports:
      - "4566:4566"
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.122.1
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - "./monitoring/otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml:ro"
