services:
  localstack:
    image: localstack/localstack:3.0
    environment:
      - SERVICES=sqs,dynamodb,lambda,iam
      - EDGE_PORT=4566
      - LAMBDA_DOCKER_NETWORK=simple_platform_setup_default
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEBUG=1
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.122.1
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    depends_on:
      - jaeger
      - prometheus
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    volumes:
      - "./monitoring/otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml:ro"

  jaeger:
    image: jaegertracing/all-in-one:1.65.0
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"

  prometheus:
    image: prom/prometheus:v3.4.2
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - "./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"

  grafana:
    image: grafana/grafana:12.1.0
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - "./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro"
      - "./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro"
